language: java
before_install:
  - "export DISPLAY=:99.0"
  - "export TERM=dumb"
  - "sh -e /etc/init.d/xvfb start"
script: gradle check --info
after_failure:
  - "cat ./build/test-results/*.xml"
jdk:
  - oraclejdk7  

