package jfxtras.labs.repeatagenda.scene.control.repeatagenda.icalendar;

import java.time.LocalDateTime;
import java.util.Collection;

import javafx.util.Callback;
import jfxtras.labs.repeatagenda.scene.control.repeatagenda.ICalendarUtilities.ChangeDialogOptions;
import jfxtras.labs.repeatagenda.scene.control.repeatagenda.ICalendarUtilities.WindowCloseType;
import jfxtras.labs.repeatagenda.scene.control.repeatagenda.VEventImpl;

/** Interface for VEVENT, VTODO, VJOURNAL calendar components. 
 * */
public interface VComponent
{
    /**
     * Returns the collection of recurrence instances of calendar component of type T that exists
     * between dateTimeRangeStart and dateTimeRangeEnd based on VComponent.
     * Recurrence set is defined in RFC 5545 iCalendar page 121 as follows 
     * "The recurrence set is the complete set of recurrence instances for a calendar component.  
     * The recurrence set is generated by considering the initial "DTSTART" property along with
     * the "RRULE", "RDATE", and "EXDATE" properties contained within the recurring component."
     * 
     * Type T is of the type your appointment your application requires.  For JFxtras Agenda it is
     * Agenda.Appointment.
     * 
     * @param dateTimeRangeStart - Start date/time when appointments will be made
     * @param dateTimeRangeEnd - End date/time when appointments will be made
     * @return - collection of instances of type T
     * 
     * @author David Bal
     * @param <T>
     * @see VEventImpl
     */
    <T> Collection<T> makeInstances(
            LocalDateTime dateTimeRangeStart
          , LocalDateTime dateTimeRangeEnd);
    
    /**
     * Returns existing instances in the Recurrence Set (defined in RFC 5545 iCalendar page 121)
     * made by the last call of makeRecurrenceSet
     * @param <T>
     * 
     * @return - current instances of the Recurrence Set
     * @see makeRecurrenceSet
     */
    <T> Collection<T> instances();

    
    <T> WindowCloseType edit(
            LocalDateTime dateTimeOld
          , LocalDateTime dateTimeNew
          , long durationInSecondsNew
          , VComponent vComponentOld
          , Collection<T> instances
          , Collection<VComponent> vEvents
          , Callback<ChangeDialogOptions[], ChangeDialogOptions> changeDialogCallback
          , Callback<Collection<VComponent>, Void> writeVEventsCallback);
    
}
